seed: 42

data:
  frame_count: 32
  _root_gulp_dir: ???
  worker_count: 8
  pin_memory: yes
  rgb:
    segment_length: 1  # Number of (u, v) pairs in each segment
    train_gulp_dir: ${data._root_gulp_dir}/rgb_train
    val_gulp_dir: ${data._root_gulp_dir}/rgb_validation
    test_gulp_dir: ${data._root_gulp_dir}/rgb_test
    preprocessing:
      bgr: no         # Whether network inputs should be BGR rather than RGB.
      rescale: yes    # Whether to rescale input from [0, 255] to [0, 1].
      input_size: 224
      scale_size: 256
      mean: [0.485, 0.456, 0.406]
      std: [0.485, 0.456, 0.406]
    train_augmentation:
      multiscale_crop_scales: [1, 0.875, 0.75, 0.66]
    test_augmentation:
      rescale_size: 256
  flow:
    segment_length: 5  
    train_gulp_dir: ${data._root_gulp_dir}/flow_train
    val_gulp_dir: ${data._root_gulp_dir}/flow_validation
    test_gulp_dir: ${data._root_gulp_dir}/flow_test
    preprocessing:
      rescale: yes
      input_size: 224
      scale_size: 256
      mean: [0.5]
      std: [0.226]  # Mean of imagenet std
    train_augmentation:
      multiscale_crop_scales: [1, 0.875, 0.75]
    test_augmentation:
      rescale_size: 256

model:
  type: TSM
  backbone: resnet50
  weights: ???
  dropout: 0.7
  partial_bn: yes
  shift_div: 8
  non_local: False
  temporal_pool: False
  num_class: 1024

learning:
  batch_size: 64
  optimizer:
    type: SGD
    momentum: 0.9
    weight_decay: 5e-4
  lr: 0.01
  lr_scheduler:
    type: StepLR
    gamma: 0.1
    epochs: [20, 40]
  

trainer:
  gradient_clip_val: 20
  max_epochs: 80
  ddp:
    backend: nccl
  gpus: 3

  # Write metrics to tensorboard logs every X iterations
  log_every_n_steps: 10
  flush_logs_every_n_steps: 20
  weights_summary: full
  benchmark: yes


defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog