DATA_ROOT = "../../2g1n6qdydwa9u22shpxqzp0t8m/"
PICKLE_ROOT = "../../pickles"
STRIDE = 3
BATCH_SIZE = 8
WORD_EMBEDDING_SIZE = 384
NUM_VERBS = 97
NUM_NOUNS = 305 # nouns_classes_v2.csv
VERB_CLASSES = "../../epic-kitchens-100-annotations/EPIC_100_verb_classes.csv"
NOUN_CLASSES = "../../epic-kitchens-100-annotations/EPIC_100_noun_classes_v2.csv"